# This checks that the Perl scripts compile.

name: Perl compilation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" , "devel" ]
  pull_request:
    branches: [ "master", "devel" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Setup Perl environment
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.22'
      - name: Install DB_File
        run: cpanm --force DB_File || cat /home/runner/.cpanm/work/*/build.log
      - name: Check compilation linkdatagen.pl
        run: perl -c linkdatagen.pl
      - name: Check compilation vcf2linkdatagen.pl
        run: perl -c vcf2linkdatagen.pl
